= Spring Boot Camel REST 3scale QuickStart

This example demonstrates how to use Camel's REST DSL to expose a RESTful API and expose it to 3scale.

This example relies on the https://maven.fabric8.io[Fabric8 Maven plugin] for its build configuration
and uses the https://github.com/fabric8io/base-images#java-base-images[fabric8 Java base image].

The Fabric8 Maven Plugin discovers service metadata from Camel XML Context's service definition and exposes the following:

=== Service Label
* `discovery.3scale.net/discoverable`: Allows 3scale to select Services that are to be automatically exposed.

=== Service Annotations
* `discovery.3scale.net/discovery-version`: the version of the 3scale discovery process.
* `discovery.3scale.net/scheme`: this can be http or https
* `discovery.3scale.net/path`: (optional) the contextPath of the service if it's not at the root.
* `discovery.3scale.net/description-path`: (optional) the path to the service description document (OpenAPI/Swagger). The path is either relative or an external full URL.

The application utilizes the Spring http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/ImportResource.html[`@ImportResource`] annotation to load a Camel Context definition via a _src/main/resources/spring/camel-context.xml_ file on the classpath.